name: Semgrep

on:
  push:
    branches: ["main", "master", "develop"]
  pull_request: {}
  schedule:
    - cron: '0 8 * * 1'   # Mondays 08:00 UTC
  workflow_dispatch: {}    # lets you trigger manually

jobs:
  semgrep:
    name: semgrep/ci
    runs-on: ubuntu-latest
    container:
      image: semgrep/semgrep
    if: (github.actor != 'dependabot[bot]')
    steps:
      - uses: actions/checkout@v4
      - run: semgrep ci
        env:
          SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}
